### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by atikul-islam-sajib** [pyensemble/wildwood#114]
I am trying to clone the "wildwood" repository (https://github.com/pyensemble/wildwood) and import a module from it, but I'm encountering an issue with the import process. Here are the steps I followed:

git clone https://github.com/pyensemble/wildwood
and then maybe use sys.path.extend() in order to be able to import 

Then, I import "import wildwood" - it works
However, When i call "from wildwood import ForestClassifier":

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-24-0d49c2997d7c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from wildwood import ForestClassifier

ImportError: cannot import name 'ForestClassifier' from 'wildwood' (unknown location)

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by stephanegaiffas** [comment]
You can install wildwood by just using pip install wildwood, it should work just fine (we just released a new version 0.3)
