### ISSUE TITLE
Deal with sparse datasets (CSC), recode Binner class

### ISSUE THREAD

**Issue by stephanegaiffas** [pyensemble/wildwood#5]
The Binner does not seem to handle sparse matrices... so we'll need first to recode the Binner class

**Comment by yiyang-yu** [comment]
Binner of sklearn seems send identical `bin_threshold` for highly imbalanced numerical features; we need to understand why this happen and maybe code our Binner without this problem

**Comment by yiyang-yu** [comment]
since we might do #48 first...

**Comment by stephanegaiffas** [comment]
Done in #104
